- source/faq.rst
NB: I am not versed with sqlite, so this should be taken with a grain of salt.
> Suggestion for malformed DB that worked for me

- source/anti-patterns/index.rst
- source/anti-patterns/language.rst
- source/index.rst
> Add language anti-patterns

- source/anti-patterns/language.rst
> Add rec anti pattern

- source/tutorials/ad-hoc-developer-environments.rst
Some suggested edits and expansions to some sections.
> tutorial edits

- source/anti-patterns/language.rst
> <nixpkgs> anti pattern

- .gitignore
- flake.lock
- flake.nix
> Create simple flake definition

- source/tutorials/towards-reproducibility-pinning-nixpkgs.rst
* Added some more links to terms I didn't immediately know
* Expanded some explanations
* Tidied up some wording
> Edits for reproducibility tutorial

- source/tutorials/building-and-running-docker-images.rst
some small edits for the Docker tutorial
> docker edits

- source/reference/pinning-nixpkgs.rst
- source/tutorials/towards-reproducibility-pinning-nixpkgs.rst
These 2 commits remove usages of anti-patterns in examples.
> Stop using anti patterns

- source/glossary.rst
- source/tutorials/ad-hoc-developer-environments.rst
- source/tutorials/declarative-and-reproducible-developer-environments.rst
cc @zupo @zimbatm @edibopp @sixhobbits @k0001 
[rendered](https://deploy-preview-65--nixdev.netlify.app/tutorials/declarative-and-reproducible-developer-environments.html)
Fix #14 
As usual, be as brutal as possible :)
> rewrite tutorial on declarative environments

- source/tutorials/dev-environment.rst
Resolves #59.
@DamienCassou can you confirm that this fix works for you?
> Fix errors in dev environment tutorial

- source/anti-patterns/language.rst
Fixes #48 and #31
[rendered](https://deploy-preview-69--nixdev.netlify.app/anti-patterns/language.html#attr1-attr2-merge-operator)
> Merge opreator and cwd

- source/tutorials/continuous-integration-github-actions.rst
- source/tutorials/index.rst
cc @zupo @zimbatm @edibopp @sixhobbits @k0001
Fixes #45
[rendered](https://deploy-preview-75--nixdev.netlify.app/tutorials/continuous-integration-github-actions.html)
> Continuous Integration with GitHub Actions

- source/tutorials/declarative-and-reproducible-developer-environments.rst
> reproducibile shell edits

- source/index.rst
I personally found it hard to skim through details about a tutorial when
I just wanted to know what each one was about
Hope this isn't too opinionated, but thought I might as well make the suggestion
> Set maxdepth 2 to make homepage cleaner

- source/conf.py
- source/tutorials/deploying-nixos-using-terraform.rst
- source/tutorials/index.rst
- source/tutorials/install-nix.rst
cc @zimbatm @zupo @grahamc 
I haven't really tested this out, so it's a draft.
If for some reason this is incorrect nor the best practice let me know :)
[preview](https://deploy-preview-110--nixdev.netlify.app/tutorials/deploying-nixos-using-terraform.html)
> Add tutorial for deploying NixOS with Terraform

- source/tutorials/building-and-running-docker-images.rst
This will help macOS users. While alternatives are possible[1]
this is the simplest solution.
1: https://github.com/NixOS/nixpkgs/pull/115083
> building-and-running-docker-images: Set system

- source/tutorials/deploying-nixos-using-terraform.rst
Reported in https://github.com/tweag/terraform-nixos/issues/41
> terraform: mention execution mode to be local

- source/tutorials/index.rst
- source/tutorials/installing-nixos-on-a-raspberry-pi.rst
[rendered](https://deploy-preview-144--nixdev.netlify.app/tutorials/installing-nixos-on-a-raspberry-pi.html)
> Raspberry Pi tutorial

- source/faq.rst
very hard to read as the text is being wrapped
> FAQ: put sqlite commands in a codeblock

- source/conf.py
- source/tutorials/continuous-integration-github-actions.rst
- source/tutorials/index.rst
- source/tutorials/integration-testing-using-virtual-machines.rst
Fixes #111
[rendered](https://fab33bb8.nix-dev.pages.dev/tutorials/integration-testing-using-virtual-machines)
cc @zimbatm @zupo @NorfairKing
> Add tutorial for integration testing using virtual machines

- .github/workflows/ci.yml
- default.nix
- flake.lock
- flake.nix
- poetry.lock
- pyproject.toml
- requirements.txt
> Flakify with poetry2nix

- source/index.rst
- source/tutorials/ad-hoc-developer-environments.rst
- source/tutorials/building-and-running-docker-images.rst
- source/tutorials/continuous-integration-github-actions.rst
- source/tutorials/declarative-and-reproducible-developer-environments.rst
- source/tutorials/deploying-nixos-using-terraform.rst
- source/tutorials/installing-nixos-on-a-raspberry-pi.rst
- source/tutorials/integration-testing-using-virtual-machines.rst
- source/tutorials/towards-reproducibility-pinning-nixpkgs.rst
Now that we have a few tutorials, we can link the benefits directly to those!
> Link benefits 

- source/tutorials/installing-nixos-on-a-raspberry-pi.rst
> fix broken link in raspberry pi tutorial

- flake.lock
- flake.nix
> Update to latest nixpkgs and poetry2nix

- flake.lock
- flake.nix
- poetry.lock
- pyproject.toml
Update to the latest package versions.
> Update Python env

- poetry.lock
I missed a few in https://github.com/nix-dot-dev/nix.dev/pull/209, sorry!
> Add missing python env updates

- source/tutorials/ad-hoc-developer-environments.md
The multi-line shebang format confused me because shebangs are typically limited to the top line. It's unique enough to probably call attention to the first time a new user encounters it.
> Add note on multi-line shebang

- .github/workflows/ci.yml
- .gitignore
- run_code_block_tests.sh
- shell-darwin.nix
- source/_ext/extractable_code_block.py
- source/conf.py
- source/tutorials/dev-environment.md
There are a number of code samples throughout nix.dev. How do we know they still work? We don't!
This commit introduces a way for us to extract these code samples into files and then run tests against them in CI. This will hopefully help us catch regressions in future updates to nix, NixOS and/or this guide.
Additionally, I included a darwin specific nix-shell configuration that I use personally on my M1 Mac to work on this repo. Might be useful for someone.
> Proof-of-Concept for testing code samples

- source/tutorials/building-bootable-iso-image.md
> Build a bootable ISO image RITZA language edit

- source/_templates/sponsors.html
add Tweag, as I am working on major contributions this year
> update sponsor sidebar

- source/anti-patterns/language.md
recommendation: use [MyST](https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html) syntax throughout
> fix rendering issue with nested markdown

- source/tutorials/install-nix.md
Darwin no longer needs special incantations
> update installation instructions

- CONTRIBUTING.md
not surprizingly, they have a point.
I have been highlighting the very same things intuitively many times over in recent weeks, so it appears sensible to just add that to our guidelines and only highlight the additions.
> contributing: add plain language guidelines

- .github/workflows/cla.yml
fixes #321 
@domenkozar @supersandro2000
https://github.com/contributor-assistant/github-action#inputs-description
> don't lock pull request after merge

- source/recommended-reading.md
This list was provided to me by @fricklerhandwerk and sounds like a reasonable collection.
> Add section "Videos" to `recommended-reading.md`

- source/recommended-reading.md
also reorganize recommended reading
> add 'customizing packages' to recommended reading

- maintainers/README.md
NixCon experiment to run discussion within pull requests.
Draft here: https://pad.lassul.us/gshjat31S9uSDX5GwhKeOw?both
> add section for documentation team

- maintainers/how-to-contribute-to-documentation.md
that will allow to keep it under version and easily editable
> add guide to contribute to documentation in the ecosystem

- source/tutorials/nix-language.md
> Nix language tutorial: fix typos, add notes

- CONTRIBUTING.md
- source/glossary.md
Resolves https://github.com/NixOS/nix.dev/issues/377
> Fold terminology section to glossary document

- maintainers/README.md
- maintainers/collaboration.md
I left out a few items that will subsequently be opened as GitHub issues.
> Describe maintainer collaboration

- maintainers/README.md
@lucperkins now serves as team lead
fix formatting, typos, and use past tense for things of the past.
> update documentation team information

- maintainers/how-to-contribute-to-documentation.md
also fixed formatting in a separate commit, sorry for the noise.
> add "The Nix Hour" recordings to list of documentation tasks

- source/tutorials/nix-language.md
@mkaito [reported](https://github.com/NixOS/nix.dev/pull/267#issuecomment-1270076332) that the NixOS configuration is confusing, because information is lacking to understand what it does.
added another note reminding of this tutorial's objective.
added section headings to give hints where to look next.
> refine worked examples

- source/tutorials/nix-language.md
In the current text its not even for me clear what it is referring to. This rewrite tries to give more examples for each concept of the language.
> nix-language: attempt to simplify concept overview

- source/tutorials/installing-nixos-on-a-raspberry-pi.md
small addition, otherwise people reboot and nothing changed
> You have to run nixos-rebuild switch as well

- source/tutorials/installing-nixos-on-a-raspberry-pi.md
Comment about display problems and fix with older kernel
PS: now from its own branch....sry
> Comment about display problems and fix with older kernel

- source/tutorials/nix-language.md
I came across this while doing the tutorial
> show how to exit nix repl

- maintainers/README.md
Related to https://github.com/NixOS/nixos-homepage/pull/976
> leave documentation team

- source/glossary.md
some of it got lost in 9b01513c458763b5c7c0780381b1e632356ced14
> bring back IPA pronunciation

- source/tutorials/nix-language.md
instead of a belated review of #436 by @iFreilicht
> refine wording around string interpolation

- maintainers/README.md
See also https://github.com/NixOS/nixos-homepage/pull/985
> Remove Luc and Domen from the team

- source/faq.md
This hydra cache no longer exists.
> removing snabb hydra cache

- source/tutorials/index.md
this makes it easier to digest
> limit depth of tutorials TOC

- CONTRIBUTING.md
we need an easily accessible place to guide contributors and their ideas. here is one way to do it.
@spacekookie @infinisil
> add outline to contribution guide

- source/conf.py
- source/tutorials/index.md
- source/tutorials/nix-language.md
- source/tutorials/nixos-configuration-on-vm.md
> tutorial: nixos configurations on vm

- source/conf.py
- source/contributing/index.md
- source/contributing/writing-a-tutorial.md
This work is sponsored by [Antithesis](https://antithesis.com/) ✨
> add guide to writing tutorials

- source/tutorials/reproducible-scripts.md
a shebang is not the line, just the character sequence. also it doesn't matter that much, so we may as well be brief.
> reword introduction to shebangs

- maintainers/README.md
- maintainers/working_groups/learning_journey/README.md
- working_groups/learning_journey.md
This PR establishes a Learning Journey Working Group with me as lead as requested by @fricklerhandwerk. I've also added myself as a member of the documentation team.
> Establish Learning Journey Working Group

- maintainers/google-season-of-docs-2023.md
@olaf since the project application requires a public document to link to, we better start now
> add draft for Google Season of Docs project proposal

- maintainers/README.md
> Add myself (pstn) as member.

- maintainers/working_groups/learning_journey/README.md
As mentioned on Matrix, I might not have time to participate in the meetings at the proposed time.
Let me know if this still makes sense.
> Add myself to Learning Journey WG

- .github/CODEOWNERS
I'm adding myself as a code owner for the `learning_journey` WG subdirectory so I'm notified of changes to the files in this directory.
> Add myself as a code owner for Learning Journey WG docs

- source/tutorials/ad-hoc-developer-environments.md
this addresses multiple issues observed in user studies, in order to
make the first steps as smooth as possible.
> rework nix-shell tutorial

- maintainers/google-season-of-docs-2023.md
drafted in a rush, the time commitment was outsized and the compensation inappropriate.
the new scope focuses on the learning journey itself, and treats the actual writing as stretch goals.
time estimates and budget is adjusted accordingly.
@zmitchell @olaf @arouzing
> re-scope the Google Season of Docs project

- maintainers/working_groups/learning_journey/documentation-survey.md
@fricklerhandwerk recently made available his most recent documentation survey. This PR adds a formatted version to the Learning Journey WG subdirectory for reference purposes.
> Add updated documentation survey

- source/contributing/how-to-get-help.md
- source/index.md
closes https://github.com/NixOS/nix.dev/issues/496
> add section on how to get help

- maintainers/README.md
After the meeting, I was informed to add myself to the contributors file. Please let me know if there are other files that need additional information amended too.
> Joining the team

- source/tutorials/first-steps/index.md
this more closely matches the current contents
> reword introduction to first steps tutorials

- source/conf.py
based on Nix documentation team [discussion on 2022-07-07][notes]
[notes]: https://discourse.nixos.org/t/2022-07-07-documentation-team-meeting-notes-4/20198
> assign copyright to NixOS Foundation

- source/tutorials/first-steps/ad-hoc-developer-environments.md
> Edit tutorial command line installing insecure package(from `python2` to `python3`)

- maintainers/documentation-project-2023.md
as discussed with @zmitchell and @henrik-ch, in order to brief project participants @JacklineYim and @roberth.
> update documentation project outline, add details

- maintainers/documentation-project-2023.md
> fix indentation yet again

- maintainers/documentation-project-2023.md
from "diataxis.fr/" to "https://diataxis.fr"
> documentation-project-2023.md: fix Diataxis link

- maintainers/README.md
- add myself
- remove stale calendar entry
- mark lucperkins as former lead
> Team page improvements

- maintainers/README.md
- source/tutorials/nixos/build-and-deploy/building-and-running-docker-images.md
That's how the rest of this repo spells it, and also how GitHub writes about itself.
> write "GitHub" with a uppercase "H"

- maintainers/working_groups/learning_journey/documentation-survey.md
Please let me know what you think. 
An especially open point is the types of tags we would use, which this template suggestion doesn't define yet. 
I appreciate any feedback on the other details and columns as well of course - thanks a lot.
By the way, a tip for beginners - this edited md page doesn't generate onto the website itself, so the easiest way to view and review this change is to navigate to the "Files changed" tab and  "Display the rich diff" - button that looks like a blank page.
> First version of the document survey table template

- maintainers/working_groups/learning_journey/documentation-survey.md
Another table entry, you can let these single pull requests for table rows build up and review them in bulk later on.
> added nix pills chapter 6.

- source/index.md
- source/tutorials/first-steps/index.md
Closes https://github.com/NixOS/nix.dev/issues/535
Screenshot:
> Improve landing page

- source/conf.py
Current Sitemap:
```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://nix.deven/acknowledgments/sponsors.html</loc>
</url>
<url>
...
```
New Sitemap:
```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://nix.dev/acknowledgments/sponsors.html</loc>
</url>
<url>
...
```
> Fix invalid sitemap

- source/reference/glossary.md
this will hopefully help with orienting beginners, as they will be made aware of where to get more information on each particular thing.
> glossary: add links to manuals and source code

- source/_static/css/custom.css
> css: fix code box colors

- source/contributing/documentation.md
- source/contributing/writing-style.md
- source/index.md
This PR addresses the first action item in today's [Documentation Team discussion](https://discourse.nixos.org/t/2023-06-19-documentation-team-meeting-notes-56/29339), pulling the writing style guidelines out into another page.
> Move writing style to separate page

- source/tutorials/first-steps/declarative-and-reproducible-developer-environments.md
This code is a slight format adaption and rebase from the PR #83  from @fzakaria .
> rebase of fzakaria pull request 83

- CONTRIBUTING.md
- source/contributing/documentation.md
- source/contributing/writing-style.md
since we wanted to have all that information in a central, visible place, this change moves all the parts that have been scattered around into the place we designated for it.
also made some small updates based on months of reviewing
> move more writing style recommendations into the public guide

- source/conf.py
Fixes https://github.com/NixOS/nix.dev/issues/611
> conf.py: Update repository url and branch

- source/_static/css/custom.css
- source/acknowledgments/index.md
- source/concepts/index.md
- source/conf.py
- source/contributing/index.md
- source/index.md
- source/recipes/index.md
- source/reference/index.md
- source/tutorials/index.md
Preview URL: https://peppy-mooncake-970688.netlify.app/
Screenshot:
> Make home page cards clickable

- maintainers/working_groups/learning_journey/documentation-survey.md
@henrik-ch please continue making PRs against `master`, such that we have the the latest state immediately visible
> add documentation survey updates

- source/tutorials/first-steps/declarative-and-reproducible-developer-environments.md
> Declarative reproducible developer environments

- maintainers/working_groups/learning_journey/documentation-survey.md
Summarize https://nixos.org/guides/nix-pills/inputs-design-pattern.html
> Document survey

- maintainers/working_groups/learning_journey/documentation-survey.md
* Update documentation-survey.md
Summarize https://nixos.org/guides/nix-pills/inputs-design-pattern.html
* Update documentation-survey.md
Fix typo
> Document survey (#624)

- source/tutorials/nixos/installing-nixos-on-a-raspberry-pi.md
Fixes #642 and correctly enables the wireless hardware
> fix boot config, correctly enable wlan firmware, update config link

- maintainers/working_groups/learning_journey/documentation-survey.md
Summarized https://nixos.org/guides/nix-pills/callpackage-design-pattern.html
> callpackage-design-pattern

- CONTRIBUTING.md
Adding in the contributing.md how a beginner can help on the documentation survey.
Addresses issue #640.
> What you can do for the documentation survey

- source/contributing/documentation.md
Addresses #639.
Please look at line [174](https://github.com/NixOS/nix.dev/blob/10b936f6d8b079cdfa75502481fe56453f301bfb/source/contributing/documentation.md?plain=1#L174) especially to make sure that it's correctly representing our intentions.
> adding nix pills to external sources.

- source/contributing/documentation.md
- source/contributing/how-to-contribute.md
- give more concrete tips on filing issues.
this is based on experience with helping to maintain Nix and trying to make sense of what's going on
in Nixpkgs.
- add pointers for making donations
> expand contribution guidelines

- source/tutorials/first-steps/reproducible-scripts.md
This is a duplicate of https://github.com/NixOS/nix.dev/pull/527 with suggestions applied. That PR is stuck so I've moved it here to merge.
> Explain chained script interpreter

- source/recipes/faq.md
Just wanted to suggest a quick typo fix without too much overhead. Is this an okay way to do it or should this be more involved?
> Fix typo in faq.md

- source/contributing/writing-a-tutorial.md
> Update diataxis links

- source/_static/css/custom.css
Closes https://github.com/NixOS/nix.dev/issues/644
> Add styles for diffs

- source/contributing/documentation.md
> Add a summary of the Diataxis framework

- source/tutorials/learning-journey/shell-dot-nix.md
This PR updates the `shell.nix` tutorial with feedback that I was supposed to wait for and forgot about.
> Tweak shell.nix tutorial

- source/tutorials/learning-journey/index.md
- source/tutorials/learning-journey/sharing-dependencies.md
> Add sharing deps tutorial

- source/tutorials/learning-journey/sharing-dependencies.md
Updating this tutorial as a follow up to [this comment](https://github.com/NixOS/nix.dev/pull/675#issuecomment-1694142533) based on the review that wasn't addressed before merging.
> Update sharing deps tutorial

- source/tutorials/nixos/index.md
- source/tutorials/nixos/integration-testing-using-virtual-machines.md
- source/tutorials/nixos/nixos-configuration-on-vm.md
this is a split off from https://github.com/NixOS/nix.dev/pull/274 
This PR focus on the document that is originally written by @domenkozar and the expansion on its topic.
> expand on nixos configuration testing

- source/recipes/faq.md
Add nixos-anywhere to tools for bootstrapping NixOS in faq.
> faq: Add nixos-anywhere to bootsrapping NixOS

- source/concepts/faq.md
- source/concepts/flakes.md
> fix broken links

- source/concepts/faq.md
- source/index.md
> move conceptual question to FAQ section

- .editorconfig
- .github/ISSUE_TEMPLATE/site.md
- .github/workflows/editorconfig.yml
- CONTRIBUTING.md
- maintainers/this-month-in-nix-docs/README.md
- maintainers/working_groups/learning_journey/README.md
- maintainers/working_groups/learning_journey/documentation-survey.md
- maintainers/working_groups/learning_journey/tutorial-outlines/sharing-dependencies.md
- source/_static/css/custom.css
- source/contributing/how-to-get-help.md
- source/index.md
- source/recipes/best-practices.md
- source/reference/pinning-nixpkgs.md
- source/tutorials/cross-compilation.md
- source/tutorials/first-steps/dev-environment.md
- source/tutorials/first-steps/nix-language.md
- source/tutorials/first-steps/reproducible-scripts.md
- source/tutorials/nixos/building-and-running-docker-images.md
- source/tutorials/nixos/continuous-integration-github-actions.md
- source/tutorials/nixos/integration-testing-using-virtual-machines.md
- source/tutorials/nixos/nixos-configuration-on-vm.md
> Add EditorConfig file and fix errors

- source/tutorials/nixos/nixos-configuration-on-vm.md
this mainly does some reformatting, rewording, and adding links
the change concerning lookup paths could make it block on #747.
if that doesn't get resolved quickly, we can merge these changes without the rename
> clean up detailed explanation on building VMs

- source/tutorials/cross-compilation.md
remove references to "towards reproducibility" as that's not very
focused, and at that point readers will likely be familiar with the
concept such that they only need the reference, if anything
> add introduction to cross compilation tutorial

- maintainers/working_groups/learning_journey/README.md
I've enjoyed participating in the docs team but lately I haven't had the time to attend the meetings and contribute.
My interests lie elsewhere in Nix at the moment and I would like to dedicate my time to exploring them.
> removing brianmcgee from learning journey working group

- source/contributing/how-to-contribute.md
this is where the information will be most up-to-date and where it
should be maintained to begin with.
> refer to contributing guides in the respective projects

- maintainers/README.md
Follow up to https://github.com/NixOS/nixos-homepage/pull/1136/
> team membership list follow up

- source/recommended-reading.md
- source/tutorials/nixos/index.md
Added link to the unofficial NixOS and Flakes book written by @ryan4yin .
> This cute world NixOS and Flakes unofficial book

- source/concepts/faq.md
As mentioned in https://github.com/NixOS/nix.dev/pull/744#discussion_r1384292320
> Less confusing stable channel recommendation

- source/tutorials/nixos/nixos-configuration-on-vm.md
add paragraph on reproducible nixos-generate-config command
> vm change to reproducible command

- source/tutorials/file-sets.md
> Fix link anchor typo

- source/guides/recipes/sharing-dependencies.md
the contents do not really warrant a full-blown tutorial
> reduce the sharing dependencies tutorial to a guide

- .github/CODEOWNERS
As proposed by @infinisil [here](https://github.com/NixOS/nix.dev/pull/818#issuecomment-1831071919).
@yukiisbored let me know if you want to be added too.
> Add asymmetric to CODEOWNERS for workflows

- source/tutorials/first-steps/declarative-shell.md
not that important but could save some time for beginners who try to install new packages and fail (like me :p)
> updated channel version

- source/tutorials/packaging-existing-software.md
The releases page is empty, and that might confuse people.
> Refer to the tags page

- source/tutorials/cross-compilation.md
cross compilation tutorial.
for #855 .
> fix for issue with host platform determination

- source/tutorials/cross-compilation.md
> simplify config.guess line

- source/tutorials/first-steps/ad-hoc-shell-environments.md
- source/tutorials/first-steps/reproducible-scripts.md
this way it's easier to find and probably also remember
> highlight recommendation to use search.nixos.org

- source/tutorials/first-steps/declarative-shell.md
make shorter sentences and drop the key message about sharing
declarative environments
> reword shell.nix tutorial introduction

- source/tutorials/first-steps/index.md
it doesn't make sense that we continue with reproducibility becuase we
haven't seen lookup paths yet.
> move shell.nix tutorial up

- source/recommended-reading.md
- source/reference/index.md
- use more neutral phrasing
- add nix-community, a lot of stuff going on there
- put the Glossary on top
> clean up the Reference side bar

- source/tutorials/module-system/module-system.md
- source/tutorials/nixos/building-and-running-docker-images.md
- source/tutorials/nixos/building-bootable-iso-image.md
- source/tutorials/nixos/index.md
- source/tutorials/nixos/integration-testing-using-virtual-machines.md
- source/tutorials/nixos/nixos-configuration-on-vm.md
it makes more sense to start with the most innocent ones, where
everything runs in a VM.
@olafklingt
> reorder NixOS tutorials

- default.nix
now tested with:
nix build && nix-shell -p netlify-cli --run "cd result; netlify dev"
> actually fix mutable shortlinks

- source/conf.py
- source/contributing/documentation/index.md
- source/contributing/how-to-contribute.md
- source/contributing/how-to-get-help.md
- source/index.md
- clarify a few phrases
- move Open Collective link to the top
- add section headings for easier navigation
- add a few details on contacting people
> update contributing guides

- source/contributing/documentation/writing-a-tutorial.md
- fix some small details
- fix the tracking issue link
- deduplicate notes on how to explore a topic
> reword tutorial-writing guide

- source/guides/recipes/dependency-management.md
- source/guides/recipes/direnv.md
- source/guides/recipes/python-environment.md
- source/guides/recipes/sharing-dependencies.md
This PR mainly updates the examples in the guides section to newer releases.
> Update guides OS

- .github/CODEOWNERS
- CONTRIBUTING.md
- maintainers/documentation-survey.md
- source/contributing/documentation/index.md
(Edited by @infinisil:) Adds a section on how people can help with nix.dev
> Add what you can do to help section

- .github/workflows/build-and-deploy.yml
Reverts NixOS/nix.dev#906
This doesn't work, see #932
> Revert "run preview deployments on forks as well"

- source/tutorials/first-steps/declarative-shell.md
Very minor grammar issue. Noticed while reading the docs.
> fix: minor grammar correction

- source/guides/faq.md
- source/guides/recipes/python-environment.md
- source/guides/recipes/sharing-dependencies.md
- source/tutorials/callpackage.md
- source/tutorials/index.md
- source/tutorials/packaging-existing-software.md
> migrate and update `callPackage` tutorial

- source/index.md
There is a small grammar issue on `index.md`.  This  commit makes a minor correction to the heading sentence of the "What can you do with Nix" section.
> Fix a small grammar issue on index.md

- maintainers/google-season-of-docs-2024.md
cc @fricklerhandwerk 
I tried keeping this as close as possible to the official template https://developers.google.com/season-of-docs/docs/org-proposal-template
> add google season of docs 2024 propsal

- source/tutorials/nixos/building-bootable-iso-image.md
There is another guide to create an ISO. I did not exactly know how to link, thus I just added it to "Next steps".
> Link to guide from the wiki

- CONTRIBUTING.md
all the information is alreaady in the contributing guide on the website
> deduplicate CONTRIBUTING.md

- source/tutorials/cross-compilation.md
Mostly update of the channel references. 
Minor fixes to <nixpkgs>  -> nixpkgs
and moving a code comment into the the tutorial text.
> update cross compiling tutorial to 23.11

- vale/Vocab/Nix/accept.txt
attempt to pass a heading with a lot of names through vale ci test
> add names to vale

- source/guides/faq.md
- source/guides/recipes/add-binary-cache.md
- source/guides/recipes/index.md
Moved:
- [How do I add a new binary cache?](https://nix.dev/recipes/faq#how-do-i-add-a-new-binary-cache)
to a new Nix entry under guides/recipes.
> Move "How do I add a new binary cache?" FAQ to Nix recipes

- _redirects
- source/reference/nix-manual.md
this avoids exposing an ugly URL and allows us to move things
around later
Made with @roberth at #ZurichZHF
> proxy development version of the Nix manual

- .gitignore
- CONTRIBUTING.md
- README.md
- default.nix
running devmode with `--run` doesn't actually work, it doesn't pick up
the changes
Made with @roberth at #ZurichZHF
> update contributing instructions

- _redirects
- source/concepts/faq.md
- source/tutorials/nix-language.md
there are clearly too many moving parts that aren't automatically tested...
> redirect the entire mutable URL

- default.nix
- source/reference/nix-manual.md
> offer the Nix manual as a single page again

- source/tutorials/working-with-local-files.md
Closes https://github.com/NixOS/nix.dev/pull/1015
Closes https://github.com/NixOS/nix.dev/issues/1002
thanks @Runningtarrens and @biscotty666 for catching it
> fix missing changes from niv to npins

- _redirects
closes https://github.com/NixOS/nix.dev/issues/971
thanks @stablejoy for the find
> fix outdated redirect

- source/tutorials/first-steps/ad-hoc-shell-environments.md
This may seem pedantic, but I found the part saying that `--run` "_executes the given Bash command_" command misleading, especially if someone new to Linux shells would read it.
This suggestion is far from being perfect, but anything else I came up with seemed either too long-winded and/or out of place.
Thank you for these great write-ups!
> Clarify wording around `nix-shell --run`

- source/conf.py
- source/tutorials/nixos/index.md
- source/tutorials/nixos/provisioning-remote-machines.md
Closes #1014
cc @fricklerhandwerk
> Add tutorial about remote provisioning with nixos-anywhere

- source/tutorials/nixos/nixos-configuration-on-vm.md
- clarify prerequisites
- update Nixpkgs release to 24.05
- remove the NixOS special cases, they are not needed
- rework a few side notes
> update NixOS VM tutorial

- .github/ISSUE_TEMPLATE/tutorial.md
https://github.com/NixOS/nix.dev/pull/1043 claimed to have one but I forgot to `git add` the new file...
> add tutorial issue template

- source/tutorials/first-steps/ad-hoc-shell-environments.md
- source/tutorials/first-steps/declarative-shell.md
- add a note how to avoid a long download after the first tutorial
- clarify side notes by putting them in a more meaningful order
> highlight long waiting time on first invocation

- source/tutorials/nixos/binary-cache-setup.md
- source/tutorials/nixos/distributed-builds-setup.md
- source/tutorials/nixos/index.md
> Create tutorial on distributed builds

- .github/ISSUE_TEMPLATE/tutorial.md
apparently there is a 200 characters length limit on the `about` field
> fix tutorial issue template

- .github/ISSUE_TEMPLATE/tutorial.md
it doesn't get rendered anyway
> don't use markdown in the issue template's about field

- source/reference/nix-manual.md
closes #1032
Thanks @AlexMilss0 for the catch!
> fix links to single-page Nix manuals

- source/tutorials/nix-language.md
when i was reading the tutorial and came across impurities, it mentioned derivations and i had totally forgotten what they were. looking back, they were mentioned once in the very beginning and lightly discusses after. i'd expect others to be like me and would appreciate a reminder.
> added details on what derivations are, added/removed periods

- nix/nix-versions.json
- nix/sources.json
- npins/sources.json
following https://github.com/NixOS/infra/pull/516
> update Nixpkgs (and Nix) releases

- source/tutorials/nixos/building-and-running-docker-images.md
actually that was an issue to add a tutorial, and that tutorial now
exists!
> fix broken link

- source/contributing/how-to-contribute.md
- source/contributing/how-to-get-help.md
thanks @antonmoisch for [bringing up](https://discourse.nixos.org/t/learning-nix-to-contribute-back/61364) the NixCon 2024 talk!
> update contributor guidance with links

- source/tutorials/nix-language.md
Update the wording of the lambda description in the function language description.
> Clarify the lambda description

- source/tutorials/module-system/deep-dive.md
Hi, 
i went through the tutorial step by step and noticed some minor errors in the code examples. With the suggested fixes everything works along the way. 
Please let me know if i can provide any further details and thank you so much for providing these learning materials! 
Best, fschn90 :wave:
> Module system: minor tutorial code fixes

- _redirects
- source/netlify.toml
This reverts commit 0441a00ee225a5ce525fbdb65a8b433f0d73d7c5.
But this time we install the netlify.toml into the root of the page.
> Reapply "Add hydra proxy header with well-known X-From (#1147)" (#1149)
