- source/index.rst
A pedantic pull-request to fix a typo on the index, `Nixkgs` => `Nixpkgs`. Inadvertently noticed while pursing the community cookbook just now.
> source/index.rst: pedantic typo fix, 'Nixkgs' => 'Nixpkgs'.

- source/tutorials/install-nix.rst
I've narrowed down the focus of installation to just installation. We could at the end provide a list of a few tutorials to continue learning about Nix.
- by default recommend daemon/multi-user installation: I think that should really be the default and then only when one can't (like Docker or obscure Linux distributions) one would fallback to single-user mode
- simplify verification by just checking Nix version
- added a note about Catalina
> Nix installation tutorial

- source/glossary.rst
- source/index.rst
- source/tutorials/ad-hoc-developer-environments.rst
- source/tutorials/first-shell.rst
- source/tutorials/index.rst
- source/tutorials/install-nix.rst
First tutorial is available as a draft!
I'd love to hear comments from @zupo @k0001 @zimbatm @brodul
> Tutorial: ad hoc developer environments

- source/anti-patterns/language.rst
This is a bit subjective for s/`/``/ replacement but even in HTML generated by Sphinx gray spans on https://nix.dev/anti-patterns/language.html look much more prominent than italic (which is easy to miss and sentences using "with" become a bit confusing)
> Minor improvements

- source/tutorials/building-and-running-docker-images.rst
- source/tutorials/index.rst
This is a minimal tutorial addressing #11. It's missing a lot of detail, but I think this is enough to get people started. Hence the reference to the `example.nix` on nixpkgs. People comfortable reading code examples without further explanation already have a starting point to do more.
* explain more aspects of `dockerTools.buildImage`:
* command parameters
* volume mounts
* exposed ports
* extending pre-built images
* ...
> Write tutorial about Docker images

- source/anti-patterns/language.rst
I was incorporating this and was scratching my head on why
```
error: error: --- EvalError ----------------------------------------------------------------------------------------------------------------------------------------------------- nix
in file: (string) (1:18)
unsupported argument 'src' to 'addPath'
```
> builtins.path expects path, not src

- source/tutorials/towards-reproducibility-pinning-nixpkgs.rst
I assume most people will try to use this in a top-level default.nix, as I did. :)
I used the GitHub editing interface, which automatically added a newline at the end of the file. I agree with that, since I hold that a file is a collection of newline-terminated lines, so I'm leaving it. If you like, though, I can fork it locally and take it out.
> Formulate niv example for use in default.nix

- source/faq.rst
nixpkgs-review is a little more featureful, and the tool I see used most often:
```
$ nox-review pr --help
Usage: nox-review pr [OPTIONS] PR
Options:
--slug TEXT           The GitHub "slug" of the repository in the from of
owner_name/repo_name.
--token TEXT          The GitHub API token to use.
--merge / --no-merge  Merge the PR against its base.
--help                Show this message and exit.
```
vs
```
$ nixpkgs-review pr --help
usage: /nix/store/c3gzcqs77cv54i7k7hr01ffdasr3d2ar-nixpkgs-review-2.3.1/bin/nixpkgs-review pr
[-h] [--eval {ofborg,local}] [-c {merge,commit}] [--post-result] [--build-args BUILD_ARGS] [-p PACKAGE]
[--package-regex PACKAGE_REGEX] [--no-shell] [--token TOKEN]
number [number ...]
positional arguments:
number                one or more nixpkgs pull request …
```
> Mention `nixpkgs-review` for reverse dependencies

- source/anti-patterns/language.rst
Knowing about that significantly increased the ergonimics
of nix-shell for me. So I think it's good to mention it.
> Refer to gitignoresource in case of ./. anti pattern

- source/tutorials/towards-reproducibility-pinning-nixpkgs.rst
When trying to follow the example, it would not work, but removing the semi-colon made it work. I am not sure if the problem is on my side, but I am taking a chance assuming the problem is in the documentation and therefore submitting this pull request.
> Remove semi-colon from fetchTarball example

- source/anti-patterns/language.rst
Hello,
It seems to me that `with` is used to reduce the repetition of fetching from an attrset, providing an alternative that simply ignores this intent does not "feel right".
Bringing attributes into scope is something that `inherit` does well, so I've been using it whenever I would use `with`.
The example I've added below the original one is something I've started doing as well whenever I want to use `with` in a list, lists don't "feel particularly good" to me a lot of the time, so I default to building an attr instead and I turn it into a list via `builtins.attrValues`. This has downsides: you can't repeat values if they have the same name, and I'm not sure if there are any guarantees in regards to the ordering. This does not matter in some cases however (`buildInputs`).
An alternative …
> Showcase `inherit` as an alternative to `with`

- source/faq.rst
Has been moved since early 2021
Now a redirect.
> Update home-manager link

- source/reference/pinning-nixpkgs.rst
- source/tutorials/deploying-nixos-using-terraform.rst
- source/tutorials/towards-reproducibility-pinning-nixpkgs.rst
I think this is pretty self explanatory, there isnt much point of keeping the website to reference an outdated channel.
> Replace all mentions of 20.03 with 21.05

- source/tutorials/cross-compilation.rst
* `nativeBuildInputs` is roughly equivalent to taking a package from `buildPackages` which
means that *its* host platform is the build platform of the derivation (so we can execute it during
the build) and its target platform is the host platform of the derivation (so e. g. compilers produce
binaries that can be executed where we want them to)
* `buildInputs` are needed on the *host* platform of the derivation
* What would the target platform be in this case? It would only be relevant if we were to build a
cross-compiler: Then we'd need runtime libraries for the target platform, for example.
> cross-compilation: fix platform terminology in shell example

- source/tutorials/install-nix.rst
This example is intentionally a bit more verbose as docker might be used
by upstream authors to test package in nixpkgs without having to install
nix.
> add short hacking tutorial for nixpkgs with docker

- source/tutorials/installing-nixos-on-a-raspberry-pi.rst
Looks like the `new_kernel` variant no longer exists.
I used the plain `nixos.sd_image` image and managed to get my RPi4 up and running with it.
> new hydra link to the aarch64 sd image

- source/faq.rst
- source/reference/pinning-nixpkgs.rst
- source/tutorials/ad-hoc-developer-environments.rst
- source/tutorials/contributing.rst
- source/tutorials/install-nix.rst
A bunch of URLs changed with the recent updates to nix/nixpkgs manuals. This PR fixes the links so they point to new URLs.
> Fix broken links after recent update to nix/nipkgs manuals

- source/tutorials/installing-nixos-on-a-raspberry-pi.rst
The dd command used an older image instead of the newer image downloaded earlier in the tutorial
> Fix image name in dd command of the raspberrypi tutorial

- poetry.lock
- pyproject.toml
- source/conf.py
- source/influences.md
For now, we can have both .rst and .md files, so we can do the convertion to Markdown file-by-file. In this PR I converted only a single file, just to show how it is done. No changes in styling.
Before:
After:
The rationale to convert to Markdown:
* less frictions for newcomers to submit patches because more people are comfortable with Markdown than ReST,
* official Nix(OS) manuals are Markdown too.
> Initial support for MyST

- source/tutorials/cross-compilation.md
From my impression that most software developers have no idea about cross compiling with `nix` before coming here (including myself), I think it is important to carefully introduce terminology and the mechanism used in `nixpkgs`.
I tried to make shorter, clearer sentences, and give some context on how and why things are the way they are.
> Clarify explanations on cross compilation

- source/tutorials/towards-reproducibility-pinning-nixpkgs.md
Two commands were formatted as quotes instead of code. This caused an issue where --branch was formatted with '–' instead of '--'. This caused an error when copying and pasting the command into a terminal:
```
[nix-shell:~/niv]$ niv modify nixpkgs –branch nixos-21.05
Invalid argument `–branch'
Usage: niv [-s|--sources-file FILE] [--no-colors] COMMAND
```
> Change quote formatting to code format on towards-reproducibility-pinning-nixpkgs

- source/tutorials/dev-environment.md
After the `nix-build` command the resulting app bin is `myapp` not `myapp.py`.
Tested on: 
macOS 12.3.1
nix-build (Nix) 2.8.0
Commands history:
```
1. nix-build
2. ls result/bin/
myapp
```
> Fixing ./result/bin/myapp.py to ./result/bin/myapp

- source/influences.md
[bob.build ](https://bob.build/docs/)is a build system written in Go, which uses nix for package management. More info [here](https://bob.build/docs/getting-started/package-management)
> add bob.build to Software Nix has influenced

- source/anti-patterns/language.md
- source/tutorials/towards-reproducibility-pinning-nixpkgs.md
remove duplication so we can link to the respective section from the
language tutorial
> rework notes on search paths

- source/index.md
- it's multiple guides
- simpler sentence structure
- now missing "developers", but no obvious way to include it in
a grammatically correct way
> update site description

- source/recommended-reading.md
removed:
- Learn X in Y minutes is barely readable and not a tutorial but an
overview
- Nix by example is from 2014, has chaotic structure, and is oriented towards functional programmers
> update list of recommended Nix language tutorials

- source/tutorials/ad-hoc-developer-environments.md
Seems this was broken in 5e0ba5f66b80401ba51c43c6230f6196d1356462.
> fix git version in example

- source/_static/css/custom.css
- source/conf.py
This implements highlighting for shell input/output. To use it, two adjacent code blocks must have `shell-session` and none as their highlighting language.
As for how to highlight it, I copied my approach from the Summer of Nix homepage (which itself is based on the German Ubuntu Wiki) and inverted the text/background colours. I’m not sure if that is the best way to handle this here, because the output also gets highlighted and might look weird with inverted colours.
Also, I noticed that Sphinx does not check if the files in `html_static_path` have changed on a rebuild, so they will not be replaced unless a full build is triggered.
cc @fricklerhandwerk
> add highlighting for shell input/output

- source/tutorials/nix-language.md
Fix the evaluation result of an example which is missing enclosing brackets.
> Fix typo in Nix language tutorial

- CONTRIBUTING.md
we observe confusion around terminology.
- newcomers find it hard to distinguish all the things that are called Nix
- Nix is a very generic term that is hard to search for online
this proposal is to introduce just enough structure to clearly distinguish concepts, and give names that are not wrong, without invalidating existing material. therefore it is strictly oriented around existing conventions.
it is *not* intended as an attempt to radically rename ecosystem components, even if that may be desirable for better readability and discoverability.
closes https://github.com/NixOS/nix.dev/issues/275
> codify terminology

- .github/CODEOWNERS
This PR adds a CODEOWNERS file to nix.dev. This PR should be interpreted largely as a springboard for inline discussion about who should own what. I've leaned heavily toward @domenkozar as the core maintainer of the bulk of this project but am fully open to suggestion on all of the above.
> Add CODEOWNERS system to nix.dev

- source/anti-patterns/index.md
- source/conf.py
- source/index.md
- source/reference/index.md
- source/tutorials/index.md
Sphinx doesn't care about filetype suffixes so we didn't see any errors.
But it's still nice to do this bit of gardening, I suppose?
> Fix leftovers from .rst -> .md migration

- source/tutorials/integration-testing-using-virtual-machines.md
According to
https://github.com/NixOS/nixpkgs/blob/70ec3b9f545e9c681e5dfcac10fcde3c4ff1eb87/nixos/doc/manual/development/running-nixos-tests-interactively.section.md#running-tests-interactively-sec-running-nixos-tests-interactively
`driverInteractive` is needed, and just `driver` indeed just runs through without giving me an interactive shell.
> integration testing: Fix attribute name for interactive testing

- CONTRIBUTING.md
- source/conf.py
- source/tutorials/building-bootable-iso-image.md
- source/tutorials/integration-testing-using-virtual-machines.md
Due to an [Sphinx issue][1], linkcheck fails on GitHub anchors for
GitHub rendered documents.
This change rewrites the anchors to the ones that can be verified by
linkcheck.
[1]: https://github.com/sphinx-doc/sphinx/issues/9016
> Rewrite GitHub anchor links to `user-content-`

- source/faq.md
- source/reference/pinning-nixpkgs.md
- source/tutorials/cross-compilation.md
- source/tutorials/declarative-and-reproducible-developer-environments.md
- source/tutorials/deploying-nixos-using-terraform.md
- source/tutorials/dev-environment.md
- source/tutorials/install-nix.md
- source/tutorials/installing-nixos-on-a-raspberry-pi.md
- source/tutorials/nix-language.md
- source/tutorials/towards-reproducibility-pinning-nixpkgs.md
Illustration of shell sessions or terminals should use shell-session.
Entire expressions should be encapsulated in code blocks, not inline code.
> Make code blocks consistent

- source/tutorials/nix-language.md
most importantly, derivations are not a special data type, but only
a certain kind of attribute set with two magic attributes.
we don't go into the details of the magic here, because it's really hard
to explain concisely. it would only distract from the surface feature
we care about here: composition through store paths.
> fix wording on derivations

- source/tutorials/nix-language.md
Closes https://github.com/NixOS/nix.dev/issues/345
@Ten0 please take a look.
> Nix language tutorial: add explanation on how `pkgs.lib` is obtained

- source/tutorials/nix-language.md
@mkaito [reported](https://github.com/NixOS/nix.dev/pull/267#issuecomment-1270076332)
that the list example was confusing and lacked explanation. thanks!
moved the example to function application, and reduced the syntax notes
to "notes on whitespace". moved the emphasis on the goals of this
tutorial to its proper place in the introduction.
it's good to leave the whitespace notes in the introductory part,
because they are unspecific and clearly belong to the "don't worry, it
may look weird, but that doesn't matter" part.
> rework parentheses example

- source/tutorials/nix-language.md
List elements separated by white space
examples were not generating correctly.
> Correction in calling functions section

- maintainers/responsibilities.md
Document maintainer responsibilities.
As discussed during the NixCon 2022 hackathon.
> Maintainer responsibilities

- maintainers/README.md
- maintainers/responsibilities.md
as discussed on the documentation team meeting.
follow-up to https://github.com/NixOS/nix.dev/pull/362
@infinisil it seems the `gh` workflow confused my muscle memory and did not do what I had expected.
> complete the overview of maintainer responsibilities

- source/reference/pinning-nixpkgs.md
- source/tutorials/dev-environment.md
The previous version is specific to Python as it uses `buildPythonApplication` instead of `mkShell`.
This one is more general but maintains the same Python Flask web application example.
> Rewrite "Set up development environment"

- source/tutorials/declarative-and-reproducible-developer-environments.md
- source/tutorials/nix-language.md
- source/tutorials/towards-reproducibility-pinning-nixpkgs.md
The pinned nixpkgs in these examples does not work with more recent versions of nix.
Fixes #419
> Update example pinned nixpkgs to a recent one

- source/tutorials/install-nix.md
With the [fish shell support](https://github.com/NixOS/nix/pull/7014) added earlier this year, Nix supports installations in fish shell out of the box. The installation instructions still use process substitution syntax that's specific to other shells (eg. bash & zsh), so users installing Nix from fish shell must translate the command before the installation will work.
This PR makes the install commands in the installation instructions compatible with fish shell.
Running the current install command in fish produces
```fish
$ sh <(curl -L https://nixos.org/nix/install)
...
fish: Invalid redirection target: 
sh <(curl -L https://nixos.org/nix/install)
^
```
Running the command with the correct fish syntax starts the installer (also tested with the `--daemon` flag passed to the installer) …
> Make install command in documentation compatible with fish shell

- source/tutorials/nix-language.md
This is in accordance with the official naming, which was [changed in Release 2.13](https://nixos.org/manual/nix/stable/release-notes/rl-2.13.html).
> Rename antiquotation to string interpolation

- source/tutorials/install-nix.md
Nix releases aren not signed any more:
https://github.com/NixOS/nix/pull/7411
nixos.org does not have the referenced section any more:
https://github.com/NixOS/nixos-homepage/pull/975
> remove notes and links to verifying Nix installation

- source/tutorials/nix-language.md
The code example has a typo. One space is missing.
Original code example produces the following output:
```
"nono no"
```
but the expected result is 
```
"no no no"
```
> fix: typo in the code example

- source/tutorials/ad-hoc-developer-environments.md
- source/tutorials/index.md
- source/tutorials/nix-language.md
- source/tutorials/nix-shell-in-shebang.md
- source/tutorials/reproducible-scripts.md
This explains how to use `nix-shell` in a shebang.
I'm open to changes to better fit nix.dev style :+1:
> add tutorial for nix-shell in shebang

- source/tutorials/nix-language.md
Called out as an anti-pattern https://nix.dev/anti-patterns/language#unquoted-urls
This change is to make the docs more self-consistent, and promote good habits in the reader.
> Quote URLs in nix language tutorial

- source/glossary.md
we should always link to authoritative definitions of terms when they
exist, instead of doing double book keeping here.
"attribute name" should be uniquely defined in the Nix reference manual.
"package name" should be uniquely defined in the Nixpkgs manual.
> remove redundant terms from glossary

- source/tutorials/nix-language.md
I was just checking out the [Nix language basics](https://nixos.org/guides/nix-language.html) and found the example of multi-line strings a bit odd as it exhibits different (and weirder) behavior than Python `"""` strings and is inconsistent with the second example. Checking with the NixOS Virtualbox image shows that in reality, the behavior is as expected and this seems to be a typo :)
> Add missing trailing newline in multi-line string example

- source/reference/pinning-nixpkgs.md
remove the NixOS example, as the sample has lots of caveats, such as
having to rebuild NixOS a second time to make it effective.
> fixups to pinning overview

- source/tutorials/cross-compilation.md
I believe this is required for the following commands to work with the pinned version of nixpkgs.
> NIX_PATH includes nixpkgs in cross-compilation.md

- maintainers/README.md
this is to make the process more discoverable. it still needs more details, but we can provide those as needed, probably in a separate document.
fixes #365
> add note on providing commit access to maintainers

- maintainers/this-month-in-nix-docs/README.md
- maintainers/this-month-in-nix-docs/make-post.sh
This PR fixes a typo in the README for using this script and removes the bold formatting around the post title generated by the script.
> Fix typos in This Month in Nix Docs script

- source/conf.py
- source/tutorials/integration-testing-using-virtual-machines.md
This PR fixes a link that was broken when an anchor in the `cachix/install-nix-action` README was changed.
> Fix link to renamed anchor

- .github/ISSUE_TEMPLATE/tracking-issue.md
This PR adds an issue template for creating new tasks. The benefit over a free-form issue in this case is that it prompts the user to fill out as much context as possible, which is often missing from free-form issues.
> Create an issue template for tracking issues

- .github/ISSUE_TEMPLATE/site.md
This PR adds an issue template for suggesting improvements to nix.dev, specifically calling out things like typos, styling, etc. This issue template is meant to narrowly cover presentation, not documentation contents.
> Create an issue template for site improvements

- source/index.md
most importantly Nixpkgs was missing.
the documentation team decided to use European English some time ago.
> update keywords and language

- source/tutorials/first-steps/nix-language.md
This phrases it a bit more accurately, while also using the word `compute` as a correct but general synonym for non-fp novices to grab on to. That said, the last sentence isn't as important to me as the prior edits.
> nix-language: Don't imply strict eval is a thing

- source/_templates/acknowledgments.html
- source/_templates/sponsors.html
- source/acknowledgments/sponsors.md
- source/conf.py
- source/index.md
Now that the site is owned by the foundation.
> Remove mention of corporate sponsors

- source/tutorials/first-steps/nix-language.md
that information should not be maintained here
Depends on https://github.com/NixOS/nix/pull/8317
> refer to Nix manual for identifier syntax

- source/recipes/best-practices.md
strictly speaking, the Nix language does not have variables because what we call "variables" in the mathematical sense are names assigned to values that do not change, but can rather have different possible but fixed values depending on context.
this change is mainly to make use of words consistent with the Nix language tutorial in order to avoid any ambiguity and confusion for beginners, who may wonder why one article says "there are no variables" and the other one liberally uses the term regardless. always using "name" makes unmistakably clear that it's a variable in the mathematical sense.
> use "name" instead of "variable" consistently

- source/concepts/flakes.md
this is indeed a frequently asked question.
the answer is an attempt to dispassionately provide factual information.
we have ample evidence that Nix beginners get confused over the state of affairs.
> FAQ: why are flakes controversial

- maintainers/working_groups/learning_journey/documentation-survey.md
Summarised https://nixos.org/guides/nix-pills/our-first-derivation.html
> Document survey

- README.md
- source/_templates/about.html
- source/index.md
- source/reference/glossary.md
Feel free to propose better wording.
Closes #536
> Change project's self-description

- source/conf.py
This is done in order to unbreak CI until a proper solution is found.
Related to https://github.com/NixOS/nix.dev/issues/631
> Ignore linkcheck on GitHub file viewer/browser

- _redirects
If anyone wants to test CF features, like redirects, without deploying:
```shell
nix shell nixpkgs#nodePackages#wrangler
nix build -L
wrangler pages dev ./result
```
There's no hot-reloading, but it's better than nothing.
> Add missing redirects

- source/influences.md
[CI is failing on the linkchecker](https://github.com/NixOS/nix.dev/actions/runs/5501183704/jobs/10024586676#step:6:141) because https://bob.build returns a 502 bad gateway error.
The new project site is at https://bobbuildtool.dev.
> fix broken bob build link

- source/tutorials/nixos/installing-nixos-on-a-raspberry-pi.md
This fixes #590 and https://github.com/NixOS/nixos-hardware/issues/651 and provides a more minimal starting setup (no `xserver`)
> Update Raspberry Pi Installing NixOS Tutorial

- maintainers/working_groups/learning_journey/tutorial-outlines/sharing-dependencies.md
This PR contains the outline for #600.
> Add outline for "sharing deps" tutorial

- source/reference/glossary.md
- source/tutorials/first-steps/nix-language.md
this collapses the "don't panic" section into a motivating introduction and gives
the document a more distinctive name.
this also addresses feedback stating that having "basics" in the title
may be misleading about the effort required to work through the
tutorial.
this also fixes a long-standing gap of not mentioning function arguments as another form of name assignment.
@NixOS/documentation-team
> Nix language tutorial: restructure introduction

- source/influences.md
- source/reference/index.md
the glossary is empty, and influences are irrelevant for the objective
of learning Nix
> remove "Software Nix has influenced"

- source/tutorials/nixos/installing-nixos-on-a-raspberry-pi.md
small note to make it easier for newcomers on the RPI tutorial.
> adding note about using etcher when on non-nixos system.

- source/recipes/faq.md
this is indeed a frequently asked question.
the answer is an attempt to impartially present the various aspects to weigh against each other.
> FAQ: should I enable flakes

- source/tutorials/index.md
- source/tutorials/learning-journey/index.md
- source/tutorials/learning-journey/shell-dot-nix.md
Creates a tutorial to complete https://github.com/NixOS/nix.dev/issues/516
> Add shell.nix tutorial

- maintainers/working_groups/learning_journey/documentation-survey.md
Summarize https://edolstra.github.io/pubs/phd-thesis.pdf Chapter 2
>  https://edolstra.github.io/pubs/phd-thesis.pdf Chapter 2

- README.md
- source/conf.py
These could also be referenced in an article's prose.
For an example, see https://line-nos.nix-dot-dev.pages.dev/tutorials/learning-journey/packaging-existing-software#a-new-command
> Add line numbers to Nix, Python code blocks

- .github/CODEOWNERS
The reasoning is:
- domenkozar has transferred ownership of the infrastructure #481
- unless someone is a team lead on a specific sub-team (as is the case for zmitchell), we (people with write access to nix.dev) should all be able to merge PRs
> `CODEOWNERS`: remove domenkozar, fricklerhandwerk

- source/conf.py
Fixes #688
The bug preventing copying the full block text is due to this regular expression in `conf.py`:
```python
copybutton_prompt_text = r"# |\$ "
```
which [does the following](https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells):
- removes the prompt from the beginning of any lines that start with it, and
- copies **only** the lines that contain the prompt(s), if they are found, or otherwise copies the full contents of the code block.
The current regex matches on the user and root shell prompts, so presumably this was originally meant to capture text from `console` or `shell-session` blocks, but actually results in the copy button ignoring **any** useful text in blocks that contain a comment (except for the comment text).
I …
> remove regex that breaks copy button

- source/tutorials/cross-compilation.md
- source/tutorials/nixos/continuous-integration-github-actions.md
Not sure if this is the right place for it, but it seemed like the most direct place to add it. I'm open to other suggestions as well.
> Add the Magic Nix Cache as an option to the GitHub Actions page

- source/tutorials/first-steps/towards-reproducibility-pinning-nixpkgs.md
It appears that in the `towards-reproducibility-pinning-nixpkgs.md` page, the monospace code formatting is used for emphasis.  This is not the intended use of this formatting, and the rest of the page uses bold for emphasis.
> Use bold instead of monospace for emphasis

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
The proposed set of changes aims to improve CI by enabling deploy previews for forks (via manual deployments to Cloudflare Pages from GitHub CI).
Before merging this change, the following needs to be done:
- Define [`CLOUDFLARE_API_TOKEN`](https://github.com/cloudflare/pages-action#generate-an-api-token) as a [repository secret].
- Define [`CLOUDFLARE_ACCOUNT_ID`](https://github.com/cloudflare/pages-action#get-account-id) as a repository secret.
- Define `CLOUDFLARE_PROJECT_NAME` as a [repository variable].
[repository secret]: https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository
[repository variable]: https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
> Enable deploy previews for forks

- source/recipes/faq.md
- source/recipes/index.md
- source/recipes/troubleshooting.md
Moved contents of:
[What to do if a binary cache is down or unreachable?](https://nix.dev/recipes/faq#what-to-do-if-a-binary-cache-is-down-or-unreachable)
[How do I fix: error: querying path in database: database disk image is malformed](https://nix.dev/recipes/faq#how-do-i-fix-error-querying-path-in-database-database-disk-image-is-malformed)
[How do I fix: error: current Nix store schema is version 10, but I only support 7](https://nix.dev/recipes/faq#how-do-i-fix-error-current-nix-store-schema-is-version-10-but-i-only-support-7)
[I’m getting: writing to file: Connection reset by peer](https://nix.dev/recipes/faq#i-m-getting-writing-to-file-connection-reset-by-peer)
from FAQs to a newly created category "Troubleshooting" under Recipes, as per:
- …
> added new category 'troubleshooting' and moved 4 faqs to it

- source/index.md
In my opinion, the link to the first steps should be the first thing a new user should see.
Indeed, the first actionnable thing for a new user should be to "just get started".
I think that putting any link before means that there are all sorts of "paths" proposed, instead of one clear path.
If possible, I would go further and make the call to action even more visible. Usually it is done with a button-like UI.
> homepage: put link to first steps at the top.

- source/tutorials/first-steps/nix-language.md
The example didn't build for me, and on the Matrix room, it was pointed out that `fetchTarball` doesn't work with `mirror://`.
I fixed the code to build, and tried to update the explanation to match.
I also added a command which builds the package.
> tutorials/first-steps/nix-language: Fix the nixpkgs example

- source/tutorials/cross-compilation.md
Hi there,
The cross compilation documentation is showing, at some point, two variations on how to get a cross-compiled package 
out of Nixpkgs. Those two versions are strictly equivalent. The only unimportant difference is what prefix of the full attribute set paths that we want, that is `(import <nixpkgs> {}).pkgsCross.aarch64-multiplatform.hello` is factored out in the variable named `pkgs`. It's arguably not very helpful, and as a reader I even found it a bit confusing, because of the nesting with the original numbered list (1., 2., etc.). Because there was an `or` there, I somehow wondered if the outer numbered list had to be considered as `and`s (the text above the list answers this question, so it's fine and unambiguous - my point is just that putting nested `or` like this has …
> Remove superfluous variation of a snippet in cross compilation doc

- source/tutorials/first-steps/nix-language.md
When reading this document as a newcomer I have no preconceived notion of what a "build task" is. This tutorial is trying to explain what a "derivation" is but then uses the term "build task" in several locations. I don't know if there is a difference between the two terms but the official terminology seems to be "derivation". I don't see any reason to confuse readers by interchanging between the two terms. 
Similarly, if there _is_ a difference between a "build task" and a "derivation" it would be helpful to explain that somewhere.
> change "build task" to "derivation" in tutorial

- source/tutorials/nixos/integration-testing-using-virtual-machines.md
proposal to replace the complicated server client test with a simple test.
... unfortunately its so simple that one doesn't have to deal with network issues at all.
> simple server client test

- source/concepts/faq.md
- source/recipes/faq.md
Moved:
- [Are there some known impurities in builds?](https://nix.dev/recipes/faq#are-there-some-known-impurities-in-builds)
from recipes/faq.md to concepts/faq.md with some minor changes/additions.
File system (ext4) bulletpoint deleted because it seems to have ended up being a different issue. See: https://github.com/snabblab/snabblab-nixos/issues/42#issuecomment-220933393
>  move question on impurities to FAQs section

- source/tutorials/nixos/nixos-configuration-on-vm.md
prompted by #768
the instructions say that the command will open a window, which naturally
requires a graphical environment. but this is very late in the process, and
will likely not be obvious in the middle of a a self-directed learning
situation.
(also some drive-by fixups)
> add graphical environment as requirement

- source/guides/best-practices.md
- source/tutorials/nixos/integration-testing-using-virtual-machines.md
this is a pattern we're using repeatedly in the tutorials but never explained.
> add best practice on reproducible Nixpkgs configuration

- .github/workflows/build-and-deploy.yml
I added this filter last minute and didn't properly test it, sorry! This made the build-and-deploy workflow never update the production version of the website, even on `master` pushes.
Tested this change properly this time on my fork:
- Push to !master branch: deploy to prod skipped: https://github.com/delroth/nix.dev/actions/runs/6747929742/job/18345154135
- Push to master branch: deploy to prod triggered: https://github.com/delroth/nix.dev/actions/runs/6747965397/job/18345263014
> ci: fix deploy-and-build production branch filter

- source/tutorials/module-system/module-system.md
NOTE: This removes line numbers, [this line](
https://github.com/nixos/nix.dev/tree/d6620ebca53a85c815b1c091b38c327fcecc7e48/source/conf.py#L60) stops having an effect.
> module-system.md: replace comments with captions

- source/guides/best-practices.md
Added some changes to `source/guides/best-practices.md`.
- Removed a bullet point.
- Simplified `rec` example.
> rephrase best practices for clarity

- source/concepts/faq.md
- source/guides/faq.md
Moved:
- [What are channels and different branches on github?](https://nix.dev/recipes/faq#what-are-channels-and-different-branches-on-github)
from recipes/faq.md to concepts/faq.md.
However, there's way too many asumptions being made I can't just yet understand/prove. One example off the top of my fingers: "Small channels (...) update faster, but require in turn more packages to be built from source.", when comparing small channels to large ones. The update part I get, the second part, I don't.
A thorough review is needed, especially for the branch part. Also, should this branch part be a question on his own?
The answer for this question is built from the following sources:
Channels' sources:
- https://nixos.org/manual/nixos/stable/#sec-upgrading
- …
> move question about channels to FAQs section

- default.nix
Was missed in #761, needed for the Flake-based nixos-homepage
> default.nix: Allow pure evaluation

- CONTRIBUTING.md
we're already close enough to the original idea that there is no need to
keep it here.
check #701 for a sketch implementation of the outline.
> remove the vision outline

- source/tutorials/first-steps/declarative-shell.md
The original reason for this pull request has mostly been resolved in https://github.com/NixOS/nix.dev/pull/793, except for the header of the section of interest. The section originally mentioned Python, then the example was updated to concern Node.js. After a little discussion, removing the specific software name from the header was suggested, so that's what I've done here.
<details><summary>Original Pull Request description.</summary>
Python is mentioned in the docs, but then the example uses Node JS. I am new to Nix, so I don't want to update the example to fully use Python, so I did the simpler change of fixing the heading and mention of Python to instead say Node JS.
If someone wants to fix the example code, or change the text to NodeJS or Node.JS, or whatever, by all means. My goal …
> Remove specific software name from header in docs

- source/guides/best-practices.md
- source/tutorials/nix-language.md
- source/tutorials/nixos/nixos-configuration-on-vm.md
depends on https://github.com/NixOS/nix/pull/9114
if that PR is merged, lookup paths will be a distinct Nix language construct with its own reference documentation.
recent additions to the Nix manual clarify the distinction between
search path and lookup path, and also document the resolution algorithm.
this clarifies a lot about how all that stuff works, and also exposes its hidden complexities, allowing us to tell a consistent story about how to use stable Nix interfaces while staying out of trouble.
> search path -> lookup path

- Makefile
addresses: https://github.com/NixOS/nix.dev/issues/796
fix comes from this comment https://github.com/sphinx-doc/sphinx/issues/3451#issuecomment-373708110
git log time format is used in comment and I ran locally with that and the copyright prints correctly...but it'll break if not building from git so use `date +%s` instead to set `SOURCE_DATE_EPOCH`; `date +%Y` also should work but wasn't sure if it needed unix time or not so just went with that to be safe
> add SOURCE_DATE_EPOCH to Makefile to fix copyright year

- maintainers/README.md
The link in this repository is not used anymore. The new link was copied from the topic in the `#docs:nixos.org` room on Matrix.
> Update documentation team meeting link

- source/tutorials/module-system/module-system.md
Some headers could not be made about module features, and that's a strong signal that those sections should be removed, IMO.
> change most headers to be about module features

- source/tutorials/file-sets.md
it's a huge diff, but it doesn't change that much:
- start with a `mkDerivation` scaffold that uses `src = ./.`
- this saves the detour with an intentionally broken derivation and
the explanation it requires
- it provides an opportunity to drop another bit of information about
`toSource`, namely that it always creates a directory in the store
- use two source files to start with, otherwise the "try one file, then
the whole directory" approach is not well-motivated
- this obviates spending words on justifying a contrived example,
it flows more naturally
- mostly use diffs to highlight the changes
- this is not a strong proposal
- the explicit-include-union example starts over, so the build-up is
manageable
- it works out quite nicely overall: since there is sufficient repetition
where we …
> review pass on tutorial sections

- source/tutorials/module-system/module-system.md
When running the package as-is the following error occurs
``geocode: line 7: $1: unbound``
This is caused because ``scripts.geocode`` does not pass the parameters down to the wrapped script ``geocode``.
```
maps-module on main 
❯ cat ./result/bin/map 
#!/nix/store/kga2r02rmyxl14sg96nxbdhifq3rb8lc-bash-5.1-p16/bin/bash
set -o errexit
set -o nounset
set -o pipefail
export PATH="/nix/store/w8lpmghccjhdml5lds2bp1w6plzjb2m4-curl-7.86.0-bin/bin:/nix/store/r4bhjqsifqkqs573a0wlrbczrykn7bcr-feh-3.9/bin:$PATH"
/nix/store/mybhaciiwyk2d6xz7mmhw99pi25qdp29-map size=640x640 scale=2 zoom=7 center="$(/nix/store/4givzyglbn99qjaqfgc9wqk6shgkfhz2-geocode/bin/geocode 'switzerland')" | feh -
```
Examining geocode, we can see the wrapper that was created with `writeShellApplication`
```
maps-module on main
❯ …
```
> tutorials: fix passing paramaters to geocode

- _redirects
at some point something moved and the redirect was forgotten
> add missing redirect

- source/tutorials/module-system/module-system.md
The current code has a number of issues.
1. realising the code results in:
```
markers=$(geocode 'New York') size=640x640 scale=2 zoom=7 ...
^-------------------^ SC2046 (warning): Quote this to prevent
word splitting.
```
2.
`$(geocode ${lib.escapeShellArg marker.location})"`
Assumes that geocode has been added to the PATH so replace with below (as per previous examples).
`${config.scripts.geocode}/bin/geocode`
3.
```
in "markers=${ lib.concatStringsSep "\\|" attributes}";
in builtins.map paramForMarker config.map.markers; 
```
The ordering of this actually creates multiple ``[markers =]`` parameters and does not use the concatenation string to join the attributes together (in effect there is only 1 attribute per call) to map, and 1 new ``marker`` created.
> tutorial: Fix the markers to build and concatenate

- .github/CODEOWNERS
- source/tutorials/file-sets.md
- Now that 23.11 is released, we can use "stable" links and channels
- Now that https://github.com/NixOS/nixpkgs/pull/266362 is merged (and backported), we can use `hasExt` to save a bunch of characters
- Set myself as codeowner of the tutorial
Also remove some outdated learning journey code owner entries.
I verified the changes to the tutorial by going through the relevant parts.
> File set tutorial updates

- source/tutorials/module-system/module-system.md
Finish the tutorial, and update some snippets to be consistent with the previously made ones.
Fix some geocode references.
Full implementation according to the tutorial, [maps-module](https://github.com/brianmcgillion/maps-module), for reference.
> tutorials: Map Module 

- _redirects
- source/guides/faq.md
Adds an FAQ entry, primarily intended as a link target for the error message introduced in nixos/nixpkgs#269551.
Given that usecase, I do want to ask how much commitment to link stability is there on nix.dev? Is there perhaps a method to create a stable link that redirects to the proper location, so that external links can remain stable even if the site structure is changed?
> add FAQ entry on how to run non-nix executables

- source/tutorials/file-sets.md
Now that https://github.com/NixOS/nixpkgs/pull/273893 is merged, the previous note isn't accurate anymore.
This work is sponsored by [Antithesis](https://antithesis.com/) :sparkles:
> File sets: Update note on `gitTracked`

- source/guides/troubleshooting.md
`nix-store --init` doesn't actually do anything [0] and is not even
documented in the Nix manual
[0]: https://github.com/NixOS/nix/blob/9651034dc26c009559cb571c813a2b8aa2bba3f1/src/nix-store/nix-store.cc#L736-L744
Note: I haven't tested the actual instructions, but this change at least doesn't make them more wrong
> remove no-op command in troubleshooting advice

- CONTRIBUTING.md
- source/conf.py
apparently it got (a lot) worse and GitHub doesn't render README files
statically any more.
> disable linkcheck for GitHub anchor links

- _redirects
- default.nix
- nix/sources.json
follow-up on #764
~~this currently won't build because the pinned versions don't have the
redirects yet, and bumping them would require an expensive local build
that may fail as it does for Hydra.~~
> use upstream page redirects for Nix manual

- .github/CODEOWNERS
I'm about to reduce workload for a while and want to drastically reduce the number of notifications.
AFAICT it's not possible to unsubscribe from team review requests, but I don't want to leave the team since I'll still be active.
therefore, instead of pinging the entire team, assign subscriptions explicitly
@alejandrosame @asymmetric @henrik-ch @infinisil @olafklingt @proofconstruction please check if this arrangement makes sense for you
> reorganise CODEOWNERS

- source/tutorials/first-steps/ad-hoc-shell-environments.md
it's quite useful and not necessarily obvious without reading reference documentation
> show nix-shell --run

- source/guides/recipes/index.md
- source/tutorials/first-steps/declarative-shell.md
automatically entering the shell is the next logical step, especially if
we have turned it on and off multiple times in a row.
> move automatic environments up, add next steps

- source/tutorials/nix-language.md
I'm a newbie, so I might be missing something, but the use of an unquoted URL here seems like it goes against the ["Best Practice" page](https://nix.dev/guides/best-practices#urls), which says to always quote URLs.
> Fix unquoted URL in "Nix language basics"

- source/contributing/how-to-contribute.md
- source/index.md
For at least two years there were ongoing debates about the target
audience of the Nix ecosystem. [Nix maintainers did not manage to
converge on a statement][0]. The marketing team is explicitly [focusing
on software developers][1], and the documentation team was supposed to
align with that [from the very beginning][2].
What was missing so far was what we mean by "software developers".
Arguably, it encompasses a particular mind set about how to deal with
computers and enough time to learn things.
And while for documentation it matters most *what* the software is doing
rather than *who* it is made for (or by), the ecosystem is a community
effort, and [people matter][3]. So far, we haven't really identified the
(eventual) boundaries of this community (at least I don't know of any
serious …
> front page: Who is Nix for?

- default.nix
closes #843 
this allows mapping cleanly from the existing mutable links on nixos.org
> add mutable shortlinks

- maintainers/README.md
- add link to inaugural announcement
- the GitHub team is the most up to date in terms of membership
- fix link to meeting notes overview
> update docs team page

- default.nix
they were missing a response status code
use 302 since those are explicitly not permanent:
https://datatracker.ietf.org/doc/html/rfc9110#name-302-found
> fix mutable shortlinks

- source/tutorials/first-steps/declarative-shell.md
- source/tutorials/packaging-existing-software.md
- make many sentences shorter
- add links
- expand on finding things
- use more domain-specific headings
- add next steps
> fix up language in the packaging tutorial

- source/tutorials/first-steps/declarative-shell.md
fixes #892
@aynsof thanks for reporting!
@nixos/documentation-team what do you think? We discussed a long time ago https://github.com/NixOS/nix.dev/issues/498#issuecomment-1507689468 to use developer-oriented tools in the examples, but this seems to keep failing due to ever so slightly elevated requirements for them to actually work.
I'm now inclined to keep examples deliberately toy-like to avoid obscuring the actual thing we want to teach.
Admittedly, this particular change adds lots of character noise, but I couldn't come up with something more elegant (brief but powerful) in the short amount of time I gave it.
Maybe someone has a better suggestion?
> declarative shells tutorial: more generic example commands

- source/tutorials/first-steps/index.md
- source/tutorials/nixos/nixos-configuration-on-vm.md
@nh2 @olafklingt follow-up on #768
with the right flags it can be started in the current terminal.
when the VM stops, it's ungarbled with `reset`.
found this when trying to test a VM configuration without all the graphical hassle:
https://nixos.wiki/wiki/Cheatsheet#Building_a_service_as_a_VM_.28for_testing.29
> use a text-only configuration for the VM tutorial

- source/contributing/documentation/index.md
See current broken link here: https://nix.dev/contributing/documentation/#wiki
This broke with https://github.com/NixOS/nix.dev/commit/8264c846ef8e492caae60304f2d4b6bd8d934c3d
> Fix link to Nix manual in contributing doc

- maintainers/documentation-project-2023.md
- source/contributing/documentation/style-guide.md
- source/tutorials/nix-language.md
Wikipedia automatically redirects mobile users to the mobile version when clicking a desktop link, but doesn't do the same the other way around. This also introduces consistency, as some Wikipedia links use the desktop version and some the mobile version.
> Replace mobile Wikipedia links with desktop ones

- source/recommended-reading.md
the good stuff was historically hard to discover.
so hard that I found a new one just today...
- add Nixology
- remove the Nix Fundamentals, because it's better covered by Nixology
- add The Nix Hour
- add NixCon
- collapse Jon Ringer's videos into one link
- link to all of Wil Taylor's videos
- re-order the "other" articles to roughly match nix.dev contents
> update recommended videos

- source/guides/recipes/dependency-management.md
- source/guides/recipes/direnv.md
- source/guides/recipes/python-environment.md
- source/guides/recipes/sharing-dependencies.md
- source/tutorials/first-steps/declarative-shell.md
- source/tutorials/nix-language.md
in our examples we never actually use the compiler toolchain stuff from
`mkShell`, so we may as well not burden users with large downloads.
It's not as slick, but arguably better practice. @infinisil I've seen you using it that way, what do you think?
Thinking further, maybe we could add (and backport) an alias to it in Nixpkgs that has a more precise name that will be easier to phase out of in a better world where Nix allows actual environments (or entire shells) and Nixpkgs provides them?
> use `nixShellNoCC` in tutorials and guides

- source/guides/faq.md
this also avoids a 403 after hammering Stack Overflow with our
linkchecker
> link to the Nix reference manual on string interpolation

- _redirects
- source/guides/recipes/python-environment.md
- source/tutorials/index.md
- source/tutorials/working-with-local-files.md
this solves a weird interaction with automatically generated section IDs
where the section heading is the same as the file name.
fixes #920
@stablejoy thanks for reporting
> change file sets tutorial URL to match document title

- source/tutorials/nixos/integration-testing-using-virtual-machines.md
- source/tutorials/packaging-existing-software.md
Hello !
This PR fix two typo I found in the documentation
> Fixing typo in `integration-testing-using-virtual-machines` and `packaging-existing-software`

- source/conf.py
this is a really annoying failure, but we probably can't do much other
than waiting for IP addresses to switch around or something...
closes #924 by sticking the head in the sand
> work around link checker being blocked

- .github/workflows/build-and-deploy.yml
fixes #553
it follows the pattern in https://github.com/NixOS/nix.dev/pull/479, where the workflows are decoupled by `workflow_run`.
according to [GitHub documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) that should do the trick of running workflows that require secrets.
there's probably no way to test this other than merging and trying out.
> run preview deployments on forks as well

- maintainers/README.md
somehow "Nix" went missing from "Nix knowledge" in some transfer. it was still there in the original announcement: https://discourse.nixos.org/t/documentation-team-flattening-the-learning-curve/20003
> add missing word in documentation team goals

- source/guides/recipes/sharing-dependencies.md
Got an error when following along example.
```
Did you mean one of callPackage or callPackages?
```
> callpackage -> callPackage

- source/tutorials/nixos/integration-testing-using-virtual-machines.md
fix nixpkgs version in examples to match previously merged update of the test function
> Update integration-testing-using-virtual-machines.md nixpkgs 22.11 -> 23.11

- source/tutorials/callpackage.md
This PR fixes the missing filename header in a code block.
> fix code block header in callpackage.md

- source/concepts/flakes.md
The statistic in
https://discourse.nixos.org/t/nix-community-survey-2023-results/33124 does also include N/A responses in the percentage, so the 58% is a bit misleading as the conclusion would be that 42% are still not using flakes. I dropped the 1/3 statement for now, because I couldn't find any information about that, but I can re-add it if this percentage is actually correct. I also dropped the 2022 results as it didn't seem to have the explicit question in it.
> correct the number of flake users

- source/tutorials/first-steps/ad-hoc-shell-environments.md
Prevent the inclusion of the dollar sign and preceding characters when copying shell commands from the documentation by wrapping them in a `console` code block.
> Improve Documentation: Exclude Prompt Characters from Copied Shell Commands

- source/tutorials/module-system/module-system.md
Bit of a nit pick but will keep the example consistent
> refactor: rename test.nix to default.nix for consistency

- source/_static/css/custom.css
I usually think that text collapsed behind a details element is difficult to recognize as such. 
This is a proposal to highlight those elements with a blue background color.
> highlight background of collapsed texts

- source/guides/best-practices.md
I believe it is more `rec`-like for those who need/like `rec`.
> best-practices: add a new tip for `rec`

- source/tutorials/packaging-existing-software.md
Update packaging-existing-software.md - fix syntax error in skeleton derivation example. 
Remove `;` from
```
{ stdenv }:
stdenv.mkDerivation {	};
```
This gives `error: syntax error, unexpected ';', expecting end of file`
Removing the semicolon:
```
nix-instantiate --eval --expr '{ stdenv }: stdenv.mkDerivation {}'
<LAMBDA>
```
> fix syntax error

- source/tutorials/packaging-existing-software.md
We apply `lib.fakeSha256` to get the right hash. But, upon removing `lib.fakeSha256`, the `lib` in the argument set becomes an unused binding. Should we delete it from the arguments then? Should there be something written in the tutorial that explains it? Also later the `hello.nix` is copied into `icat.nix` where the unbinding issue remains.
> `lib` unused binding in hello.nix

- .github/CODEOWNERS
- maintainers/README.md
- Remove mention of NixOS/documentation-reviewers team (I don't think we need this anymore now that @fricklerhandwerk is back)
- Link to https://nixos.org/community/teams/documentation.html (allows people without a GitHub account and not in the organisation to see the members)
> Minor team doc improvements

- source/tutorials/working-with-local-files.md
Hi , I am new and still learning, 
Following the wiki , during "nix-build" it throws error
in default.nix 
`sources ? import ./nix/sources.nix,`
`nix/sources.nix': No such file or directory`
before that we run npin
`nix-shell -p npins --run "npins init --bare; npins add github nixos nixpkgs --branch nixos-23.11"`
tree npins
```bash
npins
├── default.nix
└── sources.json
```
which clearly doesn't what sources.nix
after researching on its github , i found its alternative niv 
then reading its wiki and running this 
`nix-shell -p niv --run "niv init; niv add NixOS/nixpkgs -n nixpkgs -b nixos-23.11"`
tree niv
```bash
nix
├── sources.json
└── sources.nix
```
Either use niv or npin
( Or i mess up something big , and this pr just a mistake)
> Niv ? Npins?

- source/guides/recipes/add-binary-cache.md
- source/guides/recipes/post-build-hook.md
- the title was misleading, because the guide is more about hooks than S3
binary caches.
- pointed Nix manual links to a fixed version
- one sentence per line
- linked the guide on configuring a binary cache
@proofconstruction
> fix up wording on post-build-hook guide

- maintainers/documentation-survey.md
- source/concepts/faq.md
- source/concepts/flakes.md
- source/contributing/how-to-contribute.md
- source/guides/best-practices.md
- source/guides/recipes/dependency-management.md
- source/guides/troubleshooting.md
- source/install-nix.md
- source/reference/glossary.md
- source/reference/pinning-nixpkgs.md
- source/tutorials/first-steps/ad-hoc-shell-environments.md
- source/tutorials/first-steps/declarative-shell.md
- source/tutorials/first-steps/reproducible-scripts.md
- source/tutorials/module-system/a-basic-module/index.md
- source/tutorials/module-system/deep-dive.md
- source/tutorials/nix-language.md
- source/tutorials/nixos/deploying-nixos-using-terraform.md
- source/tutorials/nixos/nixos-configuration-on-vm.md
- source/tutorials/packaging-existing-software.md
- source/tutorials/working-with-local-files.md
1. A small fixup/typo over an older reference to `niv`;
2. `niv` is not exactly unmaintained - the most recent commit is from less than 2 months ago. Let's rewrite this in a more neutral manner.
> dependency-management.md: update niv references

- source/tutorials/module-system/a-basic-module/default.nix
- source/tutorials/module-system/a-basic-module/eval.bash
Hi again, 
while continuing following and learning , under Section modules 
when you run script "./eval.bash" it shows
```
{ pkgs ? import <nixpkgs> { } }:
^
error: cannot convert a function to JSON
```
can we convert function to json in nix? ( did i miss something )
so i just declared pkgs inside   "let .... in" block 
```
let
pkgs = import <nixpkgs> {};
....
in
```
after executing it shows 
```
while evaluating attribute 'name'
error: cannot convert a function application to JSON
```
after reading wiki , i followed with    **--strict**
```
nix-shell -p jq --run "nix-instantiate --eval --json --strict | jq"
```
now it does show the expected output.
```
{
"name": "Boaty McBoatface"
}
```
Please check on your end , i did double check about the error and also there might be better solution …
> JSON convert in modules error

- source/tutorials/packaging-existing-software.md
closes #1011
remove the specific channel, as search.nixos.org will deprecate old channels
> fix search link

- source/tutorials/nix-language.md
According to:
https://github.com/NixOS/nix.dev/blob/cdd059f7e5627b68a137d4de3ea98ab100bdb5a9/source/tutorials/first-steps/declarative-shell.md?plain=1#L84
>The `packages` attribute argument to `mkShellNoCC` is simply an alias for `nativeBuildInputs`.
I believe https://github.com/NixOS/nix.dev/issues/131 can be closed now. I think this is one of the last remaining instances where mkShell* uses `buildInputs`.
> fix mkShellNoCC to use `packages` instead of `buildInputs`

- source/tutorials/working-with-local-files.md
~- In union working section of [Working with local files](https://nix.dev/tutorials/working-with-local-files#union-explicitly-exclude-files), code difference is not clearly written so fix it.~
- add first build information in section of [Working with local files](https://nix.dev/tutorials/working-with-local-files#union-explicitly-exclude-files)
> Add first build information in section of working with local files

- source/tutorials/first-steps/declarative-shell.md
update version of nixpkgs used to avoid multiple-hour cache build for first-time users trying to learn Nix
> Update Nixpkgs versions in "declarative shells" tutorial

- .github/workflows/build-and-deploy.yml
- CONTRIBUTING.md
- default.nix
since we currently can't fetch the manuals as a tarball from Hydra, we
have to evaluate all the Nix releases under the sun, which takes quite
a while. most of the time this is not needed and is in the way to work
on the site, so disable it by default.
> make building the manuals optional

- source/guides/recipes/add-binary-cache.md
- source/guides/recipes/post-build-hook.md
- source/tutorials/nixos/binary-cache-setup.md
- source/tutorials/nixos/index.md
- source/tutorials/nixos/provisioning-remote-machines.md
closes #1012 
cc @fricklerhandwerk
> Add tutorial on setting up a binary cache

- source/install-nix.md
Same premise/language as https://github.com/NixOS/nix/pull/11487
The impending release of macOS 15 Sequoia will break many existing nix installs on macOS, which may lead to an increased number of people who are looking to try to reinstall Nix without noticing the open/pinned issue (NixOS#10892) that explains the problem and outlines how to migrate existing installs.
These admonitions are a short-term measure until we are over the hump and support volumes dwindle.
> add admonitions for macOS 15 Sequoia update

- source/tutorials/nixos/distributed-builds-setup.md
Added garnix to the alternatives, beside nix.build and Hercules.
Disclaimer: I started garnix. I also read the discussion [here](https://github.com/NixOS/nix.dev/pull/694), and generally agree with limiting the amount of space dedicated to commercial services, and don't want to discourage that goal. But this seems like the limited mention that people settled on as being okay, and moreover is exactly in line with the usage in this section, so it seemed to me like a reasonably contribution.
> Add garnix to alternatives

- source/tutorials/working-with-local-files.md
Should be './npins' folder instead of './nix' for coherence
> typo: no folder named 'nix' in this example

- source/tutorials/cross-compilation.md
- Closes #1054 
- Add a note explaining that later versions of `nix repl` require the `-f` flag
- Maintain the original example for compatibility with older versions
> Update nix repl syntax in cross-compilation page

- source/tutorials/nixos/binary-cache-setup.md
@Gabriella439 I did consider making it the default in the tutorial instead of adding yet another alternative to the list. What do you think?
> add `nix-serve-ng` as an alternative to set up HTTP caches

- source/tutorials/nix-language.md
the string + operator was not previously introduced and it wasn't clear that you can have more than just a variable within ${}
im doing a video series for learning the nix programming language and when i saw this part of the language tutorial, i had a hard time parsing what i was seeing. perhaps this could make it more clear. thank you!
> Added extra context in the nested string interpolation example 

- source/guides/troubleshooting.md
In spite not being too much of an issue, Nix users on Darwin have the recurrent problem of macOS [updates breaking Nix](https://gist.github.com/meeech/0b97a86f235d10bc4e2a1116eec38e7e).
It might be helpful to have it documented, even if temporarly, here until the [Nix installer workaround](https://github.com/NixOS/nix/pull/9243) gets merged.
> Add troubleshooting entry for Nix issue on macOS

- source/contributing/how-to-get-help.md
404 on `https://github.com/NixOS/nixpkgs/blob/master/.github/CODEOWNERS`, replaced it with `https://github.com/NixOS/nixpkgs/blob/master/ci/OWNERS`.
> Fix broken link

- source/concepts/faq.md
- source/reference/pinning-nixpkgs.md
superecedes #1078
@ellyxir I couldn't push to your branch to do my fixups, not sure why that is. Maybe it's because you're doing it from your master branch and your fork inherited branch protections?
Next time, could you please try to open a PR from a different branch, let's see if that helps. :)
> add info on how to get the commits and channel names to use

- source/tutorials/nix-language.md
> Nix language tutorial: mention if/else

- source/tutorials/nixos/distributed-builds-setup.md
hostPlatform alone returns an attribute set, but that setting expects a system type string
> distributed builds: use stdenv.hostPlatform.system

- source/concepts/flakes.md
Discourse was updated and seems to have changed its anchor schema, which
is apparently redirected by client-side scripts, but linkcheck doesn't run JavaScript
> fix anchor to external URL

- source/tutorials/callpackage.md
I believe there's a missing `set` at the end of this note for it to make sense:
```
The resulting attribute set is now recursive (by the keyword rec). That is, attribute values can refer to names from within the same attribute [set].
```
> Add missing word in callpackage.md

- source/tutorials/nix-language.md
Proposing to move the "_Indented strings_" section after "_String interpolation_" because I think it fits better there logically. Also added a note that string interpolation works in indented strings as well.
> Move section on indented strings after string interpolation

- source/tutorials/first-steps/reproducible-scripts.md
Prompted by https://github.com/NixOS/nix.dev/issues/1096
It may not be immediately obvious that the paragraphs following the code sample explain the invocation parameters. Making them a list should let that part stand out enough to slow down reading a bit.
> shebang scripts: clarify explanation of parameters using formatting

- source/tutorials/module-system/deep-dive.md
The Regex format is wrong, it wants to say that the last two components (AA) are optional, but that needs a n optional group. At least for me on lix - but this also rhymes with my understanding of regexes.
```bash
❯ nix --version
nix (Lix, like Nix) 2.92.0
System type: aarch64-darwin
Additional system types: aarch64-darwin, x86_64-darwin
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /Users/dwt/.config/nix/nix.conf:/Users/dwt/.nix-profile/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/jgg7r6y6zz7lj84n1x4l8g8n25n3mpky-lix-2.92.0/share
```
> Fix wrong use of ? quantifier in regex

- _redirects
This makes the `/manual/nix/development/` redirect point to the latest build again. The `nix` package does not list the manual as a hydra build product anymore since it has become a link farm and/or multi-derivation package.
> _redirects: Fix /manual/nix/development redirect

- source/guides/recipes/continuous-integration-github-actions.md
For reasons beyond Determinate Systems' control, explained [here](https://determinate.systems/posts/magic-nix-cache-free-tier-eol/), the `magic-nix-cache-action` has now become the `flakehub-cache-action` for most users, which is not free in most cases. This makes it a poor fit for nix.dev as a community learning resource, and unfortunately the best course of action is to remove it from the CI guide.
> Remove Magic Nix Cache Action from continuous integration guide

- source/concepts/flakes.md
The link was https://nix.dev/manual/nix/stable/contributing/experimental-features.html.
Remove the `.html` extension so that it points to the right link on Nix manual.
> docs(flakes): fix broken link to nix manual

- source/guides/recipes/continuous-integration-github-actions.md
We removed the documentation about Magic Nix Cache Action in https://github.com/nixos/nix.dev/commit/e779898888db5b780882c9867e528cbce30ac1c1, but didn't remove this tantalizing reference to it. (At least, I think that's what this comment is about.)
> Remove vestigial reference to the Magic Nix Cache Action.

- source/guides/recipes/post-build-hook.md
All these `<h1>`s were semantically incorrect (they're part of the "Setting up post-build hooks" recipe), and they were messing up our recipe list by appearing as top level recipes on
<https://nix.dev/guides/recipes/>.
> Move post build hook headers down a layer

- nix/nix-versions.json
I believe this is all that's needed, but `nix-build .` output looked broken, containing placeholders like `@nix-latest@`. Is that normal?
> update Nix releases

- source/install-nix.md
Since we're providing for download `.tar.xz` binary tarballs, we assume that systems have xz-utils or similar for handling that compression format.  We should make a note of this small requirement at the beginning of the Install Nix page.
Ref for WSL :
```
PS C:\Users\thadg> wsl
thad@MarsOrBust:/mnt/c/Users/thadg$ curl -L https://nixos.org/nix/install | sh -s -- --daemon
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100  4267  100  4267    0     0    880      0  0:00:04  0:00:04 --:--:--  5216
sh: you do not have 'xz' installed, which I need to unpack the binary tarball
```
Fixed after running `sudo apt install xz-utils` for my Debian …
> Add note about xz requirement for tarball in install-nix.md

- default.nix
While figuring out the best name to export the nixos/nixpkgs manuals utility for out-of-tree usage, the contents of https://github.com/NixOS/nixpkgs/blob/8f6ee3a6da7025c06936fdfbdfb7ba423c3ce5d5/pkgs/tools/nix/web-devmode.nix are pasted into the overlay.
Closes #787.
> reuse `devmode` utility from nixos/nixpkgs manuals

- source/tutorials/packaging-existing-software.md
closes #1125
@joyously thanks for pointing out the issue. I removed the, IMO superfluous, part that hedges against readers introducing a syntax error. Does this make things clearer?
> simplify note on lazy attribute access

- source/guides/recipes/autoformatting.md
- source/guides/recipes/index.md
Ping @NixOS/nix-formatting, since I can't see to add the team as a reviewer on this PR.
We now have some decent tooling around this, but it's not very discoverable for people new to nix. We (the formatting team) believe `nix.dev` is a good place for this documentation to live.
I copied this text (with slight modifications) from `nix eval --raw nixpkgs#nixfmt-tree.meta.longDescription`.
> Add some documentation about the official nix formatter

- CONTRIBUTING.md
- source/tutorials/packaging-existing-software.md
* Replace nix-build output in tutorial for packaging existing software. Previous output does not match current output, and uses different hash formats. Output and hash has been updated.
* Update the port in CONTRIBUTING.md the local server runs at from 5500 to 8080 which is what it was when I ran with no changes.
Resolves issues raised in #1135
> Update nix-build output in packaging-existing-software.md, update port in CONTRIBUTING.md

- source/conf.py
With those changes, `make pdflatex` produces a well-formatted PDF document, see the [nixpkgs-cookbook.pdf](https://github.com/user-attachments/files/20040807/nixpkgs-cookbook.pdf) as an example I just built.
You might consider including the resulting PDF in the CI workflow and link it from the deployed website.
> Fix LaTeX build

- _redirects
- default.nix
- netlify.toml
On the third try I now checked the build process, and we now copy the netlify.toml into the build result. No idea how that works for the _redirects file in the repo root.
> Pass X-From header when reverse-proxying hydra

- source/_static/css/custom.css
Before ([URL](https://nix.dev/search.html?q=nix#n)):
After (with proposed changes):
> Fix search container margin causing unintentional element overlap
